#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


# Roda o phpstan
./vendor/bin/phpstan

if [ $? -ne 0 ]; then
    echo "Opa! phpstan com erros, corrija todos os erros antes de continuar..."
    exit 1;
fi

# Roda os testes
echo "Rodando testes, por favor aguarde..."
php artisan test --parallel

if [ $? -ne 0 ]; then
    echo "Opa! Algum teste não passou, corrija seus testes antes de continuar..."
    exit 1;
fi


# Formatar cada arquivo alterado usando laravel pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true
FORMATTING_ISSUES=false

echo "Checando formatação, por favor aguarde..."
echo ""

for FILE in $STAGED_FILES
do
    ./vendor/bin/pint --test "${FILE}"

    if [ $? -ne 0 ]; then
        echo "Opa! O arquivo ${FILE} não está bem formatado. Corrija a formatação antes de continuar..."
        FORMATTING_ISSUES=true
    fi
done
if [ "$FORMATTING_ISSUES" = true ]; then
    exit 1;
fi

exit 0;
